spring:
  cloud:
    stream:
      bindings:
        TemperatureOutput:
          destination: temperatureTopic
        WindOutput:
          destination: windTopic
        WaterLevelOutput:
          destination: waterLevelTopic
        PrecipitationOutput:
          destination: precipitationTopic
        HumidityOutput:
          destination: humidityTopic
        VisibilityOutput:
          destination: visibilityTopic
        PressureOutput:
          destination: pressureTopic
        ServiceRegistrationOutput:
          destination: registrationTopic