spring:
  cloud:
    stream:
      bindings:
        TemperatureInput:
          destination: temperatureTopic
        VisibilityInput:
            destination: visibilityTopic
        WindInput:
            destination: windTopic
        HumidityInput:
          destination: humidityTopic
        WatelLevelInput:
            destination: waterLevelTopic
        PressureInput:
            destination: pressureTopic
        PrecipitationInput:
          destination: precipitationTopic
        BatchOutput:
          destination: batchOutput
        ServiceRegistrationOutput:
          destination: registrationTopic
